# coding: utf-8

"""
    Authentication API

    API for user authentication  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.login_api import LoginApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login_normal_login_post(self):
        """Test case for login_normal_login_post

        User login  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
