# coding: utf-8

"""
    Authentication API

    API for user authentication  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.login_normalLogin_body import LoginNormalLoginBody  # noqa: E501
from swagger_client.rest import ApiException


class TestLoginNormalLoginBody(unittest.TestCase):
    """LoginNormalLoginBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginNormalLoginBody(self):
        """Test LoginNormalLoginBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.login_normalLogin_body.LoginNormalLoginBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
